name: Talent D.fferenTly
favicon: null
layout_spectrum: 0.24952
typography_spectrum: 0.75626
title: BOT - Powered to automate HR and Talent management tasks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6a6b6f'
    - '#484b50'
    - '#2d2d2d'
    - '#689bc5'
  brandStrength: 1
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
