name: Talent D.fferenTly
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75241
title: BOT - Powered to automate HR and Talent management tasks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
