name: Talent D.fferenTly
favicon: null
layout_spectrum: 0.35960447508841753
typography_spectrum: 0.9298802067060024
title: BOT - Powered to automate HR and Talent management tasks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.665953113231808
  lightness: 0.14196501090191305
  saturation: 0.5870580631308258
  rhythmicContrast: 0.575641565490514
purpose: []
