name: Talent D.fferenTly
favicon: null
layout_spectrum: 0.2553
typography_spectrum: 0.75626
title: MEET TANIL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc0001'
    - '#000000'
    - '#ffffff'
    - '#0a91d1'
    - '#626569'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
